{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olep.serviceAccountName" . }}
  labels:
{{ include "olep.labels" . | nindent 4 }}
{{- end -}}
